# Generated by Django 5.1.1 on 2024-09-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaches',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaches',
            field=models.ManyToManyField(to='main_app.course'),
        ),
    ]
