# Generated by Django 5.1.1 on 2024-09-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_teacher_teaches_teacher_teaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaches',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
    ]
