# Generated by Django 5.1.1 on 2024-09-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to='images/shop/')),
            ],
        ),
    ]
