# Generated by Django 5.1.1 on 2024-09-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_shopmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teaches',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
