# Generated by Django 5.1.1 on 2024-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_profile/'),
        ),
    ]
